name: Test workflow

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Ref name = <<"
          echo ${{ github.ref_name }}
          echo ">>"
          